version: "0.2"
ignorePaths: [ "node_modules", "dist", "build", "coverage", "vendor", "public", "out", ".next", ".nuxt", ".cache" 
  , ".vscode-test", ".vscode", "cspell.config.js", "cspell.json", "cspell.json5", "cspell.yaml", "cspell.yml" ]
  
dictionaryDefinitions: []
dictionaries: []
words:
  - acromial
  - AMFR
  - Azúcar
  - biggaysanta
  - bodyworker
  - Borge
  - brachii
  - budparr
  - devcontainers
  - disqus
  - DOCO
  - Egil
  - epicondyle
  - epicondylitis
  - fastq
  - flexbox
  - goldmark
  - headlessui
  - hypostatic
  - infraspinatus
  - infraspinous
  - jridgewell
  - knobber
  - Kodaiko
  - Koja
  - loong
  - Myofascia
  - nfraspinatus
  - nodelib
  - Ochsner
  - openharmony
  - parseargs
  - paulbrown
  - paulbrowncmt
  - pbmt
  - Peasy
  - pedi
  - pexels
  - pkgjs
  - Refsnes
  - riscv
  - safelist
  - scandir
  - signup
  - subscapularis
  - supraspinatus
  - supraspinus
  - teres
  - theracane
  - twrm
  - Venmo
  - wcsm
  - webp
  - xlarge
  - xxlarge
  - xxxlarge
ignoreWords: []
import: []
