version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acromial
  - AMFR
  - Azúcar
  - biggaysanta
  - bodyworker
  - Borge
  - brachii
  - disqus
  - Egil
  - epicondyle
  - epicondylitis
  - goldmark
  - headlessui
  - hypostatic
  - infraspinatus
  - infraspinous
  - knobber
  - Kodaiko
  - Koja
  - Myofascia
  - nfraspinatus
  - Ochsner
  - paulbrown
  - paulbrowncmt
  - pbmt
  - Peasy
  - pedi
  - pexels
  - Refsnes
  - signup
  - subscapularis
  - supraspinatus
  - supraspinus
  - teres
  - theracane
  - twrm
  - Venmo
  - wcsm
  - webp
ignoreWords: []
import: []
