version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Azúcar
  - biggaysanta
  - Borge
  - Egil
  - Kodaiko
  - Koja
  - Myofascia
  - Ochsner
  - paulbrown
  - paulbrowncmt
  - Peasy
  - pedi
  - pexels
  - Refsnes
  - signup
  - twrm
  - Venmo
  - wcsm
ignoreWords: []
import: []
