baseURL = 'https://paulbrown.net/'
languageCode = 'en-us'
sectionPagesMenu = 'main'
title = "The Sacramento Massage Therapist"
[Params]
subtitle = 'Paul-Porter Brown, CMT'
author = 'Paul-Porter Brown, CMT'

