baseURL = 'https://paulbrown.net/'
languageCode = 'en-us'
sectionPagesMenu = 'sections'
title = "The Sacramento Massage Therapist - Paul Brown, CMT"

[Params]
subtitle="The Online Home of Zero Point Advanced Myofascial Release"

author = 'Paul-Porter Brown, CMT'
[menus]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Book Now!"
    url = "https://paulbrown.noterro.com/"
    weight = 20
    title = "Time to Book Your Session with Paul!"

  [[menu.main]]
    name = "Buy eGift Cards"
    url = "https://app.squareup.com/gift/BGPPNS6KGJ7WM/order"
    weight = 35
    title = "A Session with Paul Makes the Perfect Gift!"

    [[menu.main]]
        name="Services"
        url="services/"
        title="Check out my service offerings  "
        weight = 40

    [[menu.main]]
        name="Blog"
        url="blog/"
        weight=50

    [[menu.main]]
        name="Contact"
        url="#contact"
        title="Get in touch!"

    [[menu.main ]]
        name="Location"
        url="#location"

    [[menu.main]]
        name = "More Info"
        weight = 99
        identifier = "more-info"

        [[menu.main ]]
            name="Massage Prep"
            url="massage-prep/"
            title="How to do a Massage Prep"
            parent="more-info"
            weight=10

        [[menu.main]]
            name="Advanced Table"
            url="advanced-table"
            parent="more-info"
            weight=20

        [[menu.main]]
            name = "Referral Program"
            parent = "more-info"
            weight = 25

        [[menu.main]]
            name="Privacy Policy"
            url="privacy/"
            parent="more-info"
            weight=30

        [[menu.main]]
            name="Terms and Conditions"
            url="terms/"
            parent="more-info"
            weight=40

